// <auto-generated />
using System;
using BlackJackService.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;

namespace BlackJackService.Migrations
{
    [DbContext(typeof(BlackJackContext))]
    [Migration("20190627092416_intial database creation")]
    partial class intialdatabasecreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview2-30571")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlackJackService.Model.Card", b =>
                {
                    b.Property<int>("Card_Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Points");

                    b.Property<int?>("Suit_Id");

                    b.HasKey("Card_Id");

                    b.HasIndex("Suit_Id");

                    b.ToTable("card");
                });

            modelBuilder.Entity("BlackJackService.Model.Player", b =>
                {
                    b.Property<int>("Player_Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Session_Id");

                    b.HasKey("Player_Id");

                    b.ToTable("player");
                });

            modelBuilder.Entity("BlackJackService.Model.Suit", b =>
                {
                    b.Property<int>("Suit_Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Suit_Id");

                    b.ToTable("suit");
                });

            modelBuilder.Entity("BlackJackService.Model.Card", b =>
                {
                    b.HasOne("BlackJackService.Model.Suit", "suit")
                        .WithMany()
                        .HasForeignKey("Suit_Id");
                });
#pragma warning restore 612, 618
        }
    }
}
